name = "fashion-pulse-scrape-trigger"
main = "index.js"
compatibility_date = "2026-07-28"

kv_namespaces = [
  { binding = "RATE_LIMIT_KV", id = "2945a69b0c7b4c5bb54bae247dbc0078" }
]

[triggers]
crons = ["0 23 * * *", "0 8 * * *"] # 08:00 KST, 17:00 KST
